# Generated by Django 4.2.5 on 2024-04-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='geeks_field',
            new_name='email',
        ),
    ]
