# Generated by Django 4.2.5 on 2024-04-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0002_rename_geeks_field_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
    ]
