# Generated by Django 4.2.5 on 2024-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footballer', '0003_remove_buyer_email_remove_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(default='2018-01-10'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
